### ISSUE TITLE
Problem with AzureRM module

### ISSUE THREAD

**Issue by eyanson** [GrzesiekP/VerticalScaleUp#1]
Hello. I have this error when execute your script on runbook from portal.
I need install any module on automation account? Can you help me? Thanks !

Write-Error: System.Management.Automation.CommandNotFoundException: The term 'Add-AzureRmAccount' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
Add-AzureRmAccount: C:\Temp\vasfq4sh.aiz\89ec4092-e0fc-403e-8802-96a9cd566794.ps1:41
Line |
  41 |      Add-AzureRmAccount -ServicePrincipal -TenantId $servicePrincipalC …
     |      ~~~~~~~~~~~~~~~~~~
     | The term 'Add-AzureRmAccount' is not recognized as a name of a cmdlet,
     | function, script file, or executable program. Check the spelling of the
     | name, or if a path was included, verify that the path is correct and try
     | again.

**Comment by eyanson** [comment]
I recreate runbook and now work fine.
